### ISSUE TITLE
Update White Beet module via SPI/UART

### ISSUE THREAD

**Issue by AlbertoGilardoni-eaton** [Sevenstax/FreeV2G#176]
Hi,
We developed a board with the White Beet module on it and we'd like to update it from V01_01_07 EIM to V02_00_01 PNC but we don't have the Ethernet interface available, only debug UART or SPI.
Is it possible to perform the update with the StxFwUpdater tool other than Ethernet?
Or is it possible with some python implementation via SPI or via some other tool with the UART interface?
Thank you.
Best regards

**Comment by nststx** [comment]
Hi @lb-rt,

Thanks for submitting your question. As far as I'm aware the StxFwUpdater currently does not support SPI firmware updates. However internally we already used modified versions of the tool to perform SPI fwus I will take a further look into this and come back to you until the end of next week.

Best regards and thanks for your patience,
Niklas Stoffers

**Comment by lb-rt** [comment]
Hi @nststx,
Ok thank you, now I'm implementing the framing protocol to try updating it using the framing API.
But one question, to start the update process I have to send 0x11:0x41 to 2, then I just send the update file in chunks with 0x11:0x04 frames? How can the module know if the update is finished?
I don't see any size exchange, or any command to end the update.
Thanks

**Comment by lb-rt** [comment]
Hello, I tried several times using the framing protocol but with no success.
Can somebody please tell me how to update the module?
As soon as I send the 0x11:0x04 frame I receive an error 0x11:0x82 so I'm stuck...

**Comment by nststx** [comment]
Hi @lb-rt,

We now have a new version for the StxFwUpdater tool planned which will support FWU updates via SPI. We will release this version in the upcoming weeks. However if you don't want to wait that long, here's how the update process works:

Setup (do this once per update):

1. Optional: Reset the Whitebeet module. Not required but ensures that the Whitebeet is in the correct state if a previous update has failed.
2. Set time and date for the board to current datetime via command 0x12:0x40
3. Start Firmware update via command 0x11:0x41 with mode set to 2 (Start update via Framing-API)

Update loop:

1. Send FWU data frames with command 0x11:0x04
2. Periodically get the status from firmware update module via command 0x11:0x40 to check for firmware update status and progress.
3. Listen for 0x11:0x83 status packets. If the Whitebeet sends you one of those packets, you'll need to resend packets starting from the packet number specified in this status packet.
4. When you receive notification 0x11:0x80 from Whitebeet you know that FWU has finished successfully.
5. If you receive 0x11:0x81 a timeout error has occured during the update. In that case ensure that timing requirements are met and try to restart the update.
6. If you receive 0x11:0x82 the firmware update failed. This can have many different reasons including erronous update files, Whitebeet being in wrong state, missing certificates, etc. You can try to reset the Whitebeet and restart the update.

Note that the Framing API has a request-response flow. Thus especially for the setup steps you should await the response from the Whitebeet module before starting to send FWU data frames. Otherwise the Whitebeet module may still be in a wrong state for receiving update frames.

If you still have issues with updating your Whitebeet module, please let me know. In that case I will need UART logs from your Whitebeet.

Best regards and thanks for your patience,
Niklas Stoffers

**Comment by lb-rt** [comment]
Hi,
First, I can't setup datetime because the version is too old and there wasn't the time module in that version I think (the manual is the 2.11.1), if I try I get Framing Error 0xF4 (Module Unknown).
Then, I can correctly send 0x11:0x41 and receive back the ack that the command is accepted, but if I send a packet with 0x11:0x04 I receive an error 0x11:0x82.
The firmware I try to send is the WHITEBEET_ISO15118_EVSE_V02_01_00.fwu file, and I send a block of 1400 bytes.
Here's the UART log:

[whitebeet_update.txt](https://github.com/Sevenstax/FreeV2G/files/11419423/whitebeet_update.txt)

**Comment by lb-rt** [comment]
Can you maybe just confirm me that the module can't be updated via SPI? Because if it's the case I'll send them back to Codico for replacement, and since it's been 3 weeks waiting I really need to know. 
Thanks

**Comment by nststx** [comment]
Hi @lb-rt,

We released a new version of the StxFwUpdater (now called FWUTool) last week including support for SPI transfer. If possible I'd like you to try updating your WB with this tool. However you'll need a Raspberry PI to perform the update as SPI transfer is currently only supported on the Raspberry PI. Please let me know if you have a Raspberry PI available to try this out as I'm really sure that it should resolve your issue. Please also make sure to re-download the FWU file as this could be another source of the issue (file corruption). Note that we tested you scenario (update from V01_01_07 to V02_00_01) with the tool and didn't find any issues, thus I'm really hoping that this new version resolves your issue.

Best regards and thanks for your patience,
Niklas Stoffers

**Comment by nststx** [comment]
Hi @lb-rt,

If you cannot find the tool in the download area Codico maybe didn't upload it so far. I will write them an email and come back to you once I got a response. If the update works with the new version of the tool and still isn't working with your tool there's probably an issue in the way your update procedure works. However it will be difficult to help with that without the ability to see what you're actually sending on the SPI. Do you maybe have a Logic Analyzer? If you do it would be very helpful if you could capture the traffic on the SPI with it (preferably using the Software Logic as we have analyzer plugins for that which help dissect the problem faster) and send me a log file. That way I could take a look at what's currently going wrong with your update tool.

Best regards,
Niklas Stoffers

**Comment by vbudko** [comment]
Hi @lb-rt,

Please also find a capture of Ethernet frames (ETHTYPE 0x6003) with framing interface messages to update SW v01.01.07 to v02.01.00

BR, Vasily Budko
[WB_EI_update_v1.1.7-v2.1.0.pcapng.zip](https://github.com/Sevenstax/FreeV2G/files/11477700/WB_EI_update_v1.1.7-v2.1.0.pcapng.zip)

**Comment by lb-rt** [comment]
Thanks I got it, I'll test it and let you know.
Then if I still have problems with my procedure I'll send you the SPI traffic.

**Comment by lb-rt** [comment]
Hello,
I found a rpi and tried the updater but I get this error:
ModuleNotFoundError: No module named 'pylibcap'

But even in SPI I use the same MAC address as the Ethernet one, or what do I put in TARGET? Is the INTERFACE spi or spi0 or what else?

Thanks

**Comment by lho-stx** [comment]
Hey @lb-rt,

you need to install some dependencies. I have attached the requirements_spi.txt. Please install them prior to using the tool:

`pip install -r requirements_spi.txt`

Regarding the command line parameters:

You need to pass some value to the script, but it is not used when using connection mode SPI, so just insert some random number. For the interface choose SPI0.0 on the pi.

There will be updated documentation on this in the near future.

Best regards,
lho

**Comment by lb-rt** [comment]
Hello,
requirements are installed, but when I run FWUTool.py and I do as you told me I get:

[!] Please provide a MAC or IP address

So I still can't update the module

**Comment by lb-rt** [comment]
ok if I add "spi" just after python FWUtool.py and I add at least a ":" to the target address I get other errors:

Welcome to the SEVENSTAX FWU Tool 2.6

Initiating framing interface
Traceback (most recent call last):
  File "/home/pi/Downloads/Sevenstax_WHITEBEET_tools__2023_05_10/Python/StxFwUpdater_FWUtool/FWUtool.py", line 318, in <module>
    interface.initialize_framing(args.connection_mode.upper(), args.interface, args.target)
  File "/home/pi/Downloads/Sevenstax_WHITEBEET_tools__2023_05_10/Python/StxFwUpdater_FWUtool/FramingInterface.py", line 66, in initialize_framing
    self.sut_adapter.start()
  File "/home/pi/Downloads/Sevenstax_WHITEBEET_tools__2023_05_10/Python/StxFwUpdater_FWUtool/SpiAdapter.py", line 183, in start
    bus = int(temp.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by vbudko** [comment]
> 

Hello @lb-rt,

You should specify MAC address of STM32 ETH as SPI just incapsulates Ethernet frames.
If you have WB-CARRIER-BOARD-EI then the STM32 ETH MAC is printed on the label of the Evaluation board.
If you have WB-CARRIER-BOARD-EI 1.1 or WHITE-BEET-EI / WHITE-BEET-EI 1.1 modules, then STM32 ETH MAC can be found as QCA7005 MAC "minus 2". The QCA7005 MAC is printed on the label of the module as well as encoded into QR-code.

BR, Vasily

**Comment by lb-rt** [comment]
I already tried, with every MAC address, normal and -2, but always same results as above...

**Comment by lb-rt** [comment]
Sorry but I think I am really wasting my time, one tells me to put some random number and another tells me that I have to put a MAC address... I can tell you that it's not reassuring at all.
And no according to the documentation SPI does not encapsulate Ethernet frames, it encapsulates the framing protocol, it feels like no one knows what we are doing here...
Anyways, it's been more than one month that I'm trying and the module can not be updated using SPI, take it or leave it.

**Comment by lho-stx** [comment]
Hey @lb-rt,

I understand your frustration but please let us sort this out.

I copied the FWUTool to my RaspberryPi4, rerun the setup and did a firmware update. I had multiple problems:

|Problem|Fix|
|---|---|
|no module named psutils|install manually with `pip install psutils`|
|problems installing pylibpcap|install Cython prior installing pylibpcap `pip install Cython`|
|liblibc.a not found|this is a bug in pylibpcap. Create a symlink from libc.a to liblibc.a `sudo ln -s /usr/lib/aarch64-linux-gnu/libc.a /usr/lib/aarch64-linux-gnu/liblibc.a` |
|AttributeError: 'NoneType' object has no attribute 'group'|The ` -i` parameter takes `spidev0.0` as argument, not `/dev/spidev0.0`|

After applying these fixes I was able to update from v1.1.7 to v.2.1.0.

 I used the following commands to setup and run the FWUTool:

```bash
cd FWUTool
python3 -m venv .venv
source .venv/bin/activate
pip install Cython
pip install psutils
sudo ln -s /usr/lib/aarch64-linux-gnu/libc.a /usr/lib/aarch64-linux-gnu//liblibc.a
pip install -r requirements_spi.txt
sudo -E .venv/bin/python3 FWUTool.py -i spidev0.0 -t 11:22:33:44:55:66 -f ../WHITEBEET_ISO15118_EVSE_V02_00_01.fwu spi
```
Please try to replicate my setup and see if the FWUTool is working then. I attach my Whitebeet log as reference for this. Please note that the baudrate in v1.1.7 is 115200 and in v2.1.0 is 1000000.

[FWU_V1_1_7_to_V2_1_0.log](https://github.com/Sevenstax/FreeV2G/files/11626471/FWU_V1_1_7_to_V2_1_0.log)

Please let me know if following my steps solves your issues.

Thank you,
lho

**Comment by lb-rt** [comment]
Hi,
I have a RPi 3B+, I installed the OS, and already installed all requirements.
install Cython --> OK
install psutils --> error

```
ERROR: Could not find a version that satisfies the requirement psutils (from versions: none)
ERROR: No matching distribution founs for psutils
```

liblibc.a not found:
`ln: failed to create symbolic link '/usr/lib/aarch64-linux-gnu/liblibc.a': No such file or directory`

I only have this directory: /usr/lib/arm-linux-gnueabihf
So I tried the same command but using this directory and apparently it worked.

When I try the FWUTool command I get the same errors as before:

```
Welcome to the SEVENSTAX FWU Tool 2.6

Initiating framing interface
Traceback (most recent call last):
  File "/home/pi/Downloads/Sevenstax_WHITEBEET_tools__2023_05_10/Python/StxFwUpdater_FWUtool/FWUtool.py", line 318, in <module>
    interface.initialize_framing(args.connection_mode.upper(), args.interface, args.target)
  File "/home/pi/Downloads/Sevenstax_WHITEBEET_tools__2023_05_10/Python/StxFwUpdater_FWUtool/FramingInterface.py", line 66, in initialize_framing
    self.sut_adapter.start()
  File "/home/pi/Downloads/Sevenstax_WHITEBEET_tools__2023_05_10/Python/StxFwUpdater_FWUtool/SpiAdapter.py", line 188, in start
    self.spi.open(bus, device)
FileNotFoundError: [Errno 2] No such file or directory
```
So no it still can't be updated.

But really, if I can use the framing protocol in SPI for me it's ok, but no one never answered my to my comment:

First, I can't setup datetime because the version is too old and there wasn't the time module in that version I think (the manual is the 2.11.1), if I try I get Framing Error 0xF4 (Module Unknown).
Then, I can correctly send 0x11:0x41 and receive back the ack that the command is accepted, but if I send a packet with 0x11:0x04 I receive an error 0x11:0x82.
The firmware I try to send is the WHITEBEET_ISO15118_EVSE_V02_01_00.fwu file, and I send a block of 1400 bytes.
Here's the UART log:

If you explain me how to do it using framing protocol I'll try, anyways I have to implement it so I'll be stuck anyways.

**Comment by lb-rt** [comment]
I tried to install **psutil** instead of **psutils** and it was installed, however at the end errors are exactly the same.

**Comment by lho-stx** [comment]
Hey @lb-rt,

I am sorry to hear that. I did the tests with a RaspberryPi 4.
Just for my sanity: Did you enable the spidevice on your RaspberryPi with `sudo raspi-config`? What is the ouput of

`ls -l /dev/`

on your Pi?

Regarding your other questions:

The FWUTool follows this procedure:

- Setting the time (0x12 0x40), ignoring failures ( n order to support older FW versions)
- Starting the firmware updated (0x11 0x41) in mode 2
- Waiting for ACK (0x11 0x41) and storing the RxBuffer value from the response in target_window_size
- Calculate frame_payload_size from target_window_size for safety, limiting frame_payload_size to 1492 max.
- Open the firmware file

Looping until firmware file is transferred :
- sending the chunks of frame_payload_size from the firmware to the Whitebeet (0x11 0x04)
- optional: wait for ACK or BUSY and resend packet if no ACK or if BUSY was received

I would like to have  deeper look into your issue, but for this I need your assistance. I kindly ask you to create a SPI log of your failed SPI communication mentioned in [your comment](https://github.com/Sevenstax/FreeV2G/issues/176#issuecomment-1537976396) ? I prefer Saleae Logic2 or .csv files, in but KingstVIS files would be ok too.

Thank you and best regards,
lho

**Comment by lb-rt** [comment]
Hi,
No I didn't enabled anything, I thought it was done with the script.
Ok so I just tried to enable it and the tool runs but I got this error:

```
Initiating SPI on bus 0 device 0 with 12000000 MHz
Starting update process
[!] Target did not answer initial frame, check whether it has connectivity and has framing over ethernet enabled
```
I'll check again the SPI cabling, or can it be something else?

Thank you.

And for the other issue, I think we might have a Saleae so I can log the SPI communication and I send you the file asap.

**Comment by lho-stx** [comment]
Hey @lb-rt,

good to hear that you got a step further. The error now is most likely due to the wiring. You need to follow the BCM pin numbers. You can get them by running `gpio readall`. I also used the wrong pins for CS, RxReady and TxPending initially. Changing the wiring using the BCM pin numbers sorted the problem out for me. I used the following connections:

<pre>
                +-----+-----+---------+------+---+---Pi 4B--+---+------+---------+-----+-----+
                | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
                +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
                |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
                |   2 |   8 |   SDA.1 | ALT0 | 1 |  3 || 4  |   |      | 5v      |     |     |
                |   3 |   9 |   SCL.1 | ALT0 | 1 |  5 || 6  |   |      | 0v      |     |     |
                |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 1 | IN   | TxD     | 15  | 14  |
                |     |     |      0v |      |   |  9 || 10 | 1 | IN   | RxD     | 16  | 15  |
                |  17 |   0 | GPIO. 0 |   IN | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
TxPending/PD11->|  27 |   2 | GPIO. 2 |   IN | 1 | 13 || 14 |   |      | 0v      |     |     |
RxReady/PD4---->|  22 |   3 | GPIO. 3 |   IN | 1 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
                |     |     |    3.3v |      |   | 17 || 18 | 1 | IN   | GPIO. 5 | 5   | 24  |<-PB9 (NSS)
PB15----------->|  10 |  12 |    MOSI | ALT0 | 0 | 19 || 20 |   |      | 0v      |     |     |
PB14----------->|   9 |  13 |    MISO | ALT0 | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
PD3------------>|  11 |  14 |    SCLK | ALT0 | 0 | 23 || 24 | 1 | OUT  | CE0     | 10  | 8   |
                |     |     |      0v |      |   | 25 || 26 | 1 | OUT  | CE1     | 11  | 7   |
                |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
                |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
                |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
                |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
                |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
                |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
                |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
                +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
                | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
                +-----+-----+---------+------+---+---Pi 4B--+---+------+---------+-----+-----+
</pre>

I checked the README.md and there it is stating to use GPIO pin numbering, this is ambiguous and will be updated.

Best regards,
lho

**Comment by lb-rt** [comment]
Hi,
Yes I followed GPIO numbering as stated in the README page, so I'll change them to BCM numbering and I try again.
Thank you.
Alberto

**Comment by lho-stx** [comment]
Hey @lb-rt,

Maybe there is still a problem with the connection. To identify this I need to see the SPI communication. I need an csv export from either Saleae Logic2 or KingstVis (or the log file itself). There are cheap Logic analyzer compatible with Logic2 by AZ-Delivery. The Logic analyzer needs to be placed in parallel to the Whitebeet:

<pre>
           Analyzer
              │ 
              │SPI
Host-PC───────┴─────────Whitebeet
</pre>

Unfortunately I do not see any more help I can offer beyond this, without access to your specific setup. I will try to get access to a RaspberryPi 3B+ to replicate your setup 1:1 and see if I can reproduce your problems.

lho

**Comment by lho-stx** [comment]
Hello @lb-rt,

we recreated your setup with a RaspberryPi 3B+. We had no issue updating the Whitebeet. The only time we got `Warning: Received invalid size-frame header!` was when we swapped TxPending/RxReady or not connecting MISO. But we used the 64-Bit version of the RaspberryPi OS. Did you install the 32-Bit version? We will try the 32-Bit version too, but if we can not reproduce your issue, we definitely need a SPI log!

Best regards,
lho

**Comment by lho-stx** [comment]
Hey @lb-rt,

we retested with the 32-Bit installation of the OS and we where able to update the Whitebeet. So I need to have some sort of SPI log in order to inspect the issue further!

Looking forward to the SPI logs,
lho

**Comment by AlbertoGilardoni-eaton** [comment]
Hi,
I was able to get a SPI log, the wiring is exactly as in your comment above.
And in the terminal I have the same messages as before "Warning: Received invalid size-frame header!".
Nothing at all in the UART debug logs.

I tried also to swap TxPending/RxReady but same result.

[Session_0.zip](https://github.com/Sevenstax/FreeV2G/files/11785997/Session_0.zip)

**Comment by lho-stx** [comment]
Hey @AlbertoGilardoni-eaton,

please aplogize for the late response.

Yes you are right, the print should say Hz instead of MHz. The Tool runs at 12 MHz, I had no problem with it. But I will check why the manual does not matches with the tool. In the meantime you can try to use 8 MHz by changing `self.spi.max_speed_hz` in` SpiAdapter.py` to 8000000.

You might know that in order to sample a signal your sampling frequency must be twice the maximum signal frequency (due to Nyquist–Shannon sampling theorem). I need to check by myself if the whitebeet is happy when using 1.5 MHz for SPI communication, but you can also try by yourself by chaning `self.spi.max_speed_hz` in` SpiAdapter.py` to 1500000.

Best regards,
lho

**Comment by nststx** [comment]
Closing, due to inactivity. If your issue still persist, feel free to reopen.

**Comment by AlbertoGilardoni-eaton** [comment]
Yes I had to stop testing and trying because it was really taking me too much time, so in SPI I never been able to update it either via Framing Protocol or via the tool provided. I can only use the Eval board that I updated via Ethernet, and all our PCBs with the Whitebeet assembled were never used.
